name: drop_shadow
description: It's a drop shadow effect not only for images but also for any widget in Flutter.
version: 0.0.1+4
homepage: https://github.com/iisprey/drop_shadow

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
